### ISSUE TITLE
SunGridEngine compatibility needed

### ISSUE THREAD

**Issue by hjmjohnson** [nipype/pydra#247]
Support for the Sun Grid Engine (SGE) is needed.

Many public HPC systems continue to use variants of the SGE job management system

Converting `nipype` to `pydra` is a non-starter until there is some hope of it working in our HPC environment.

====
I realize this is probably a low priority, but I thought I'd put it out there as a future milestone.

**Comment by satra** [comment]
@hjmjohnson - the slurm worker should provide a template. any chance of someone from your group taking a stab at this?

the other option is to test out dask support for SGE. create a dask cluster on your cluster and then point the pydra workflow to it. see for example: https://jobqueue.dask.org/en/latest/

we have just created preliminary support for dask.

**Comment by chasejohnson3** [comment]
@satra @djarecka I am working on developing an SGE worker based on the Slurm worker. I have been able to run small tasks through the SGE worker without a problem. However, when I run a pydra pipeline splitting on a large list of input data, many SGE jobs are requested at one time, and SGE cannot handle the many simultaneous submissions. Is this a known issue with Slurm as well, or was careful consideration taken in developing the Slurm worker to avoid many simultaneous task requests that I may have overlooked?

Our High Performance Computing admin has recommended I create a queue of tasks to be submitted to SGE serially using python's queue module, so I am currently deviating from the existing Slurm worker to accommodate serial rather than parallel SGE submissions. Do you have a recommendation on how to approach this issue of overwhelming SGE/Slurm?

**Comment by satra** [comment]
@chasejohnson3 - this is also an issue with slurm. there is a `max_jobs` parameter, which controls the number of job submissions. (https://github.com/nipype/pydra/blob/master/pydra/engine/workers.py#L184)

a good upgrade would be for the worker to collect jobs up to a certain time limit, and then submit all those jobs as an array job. but that's a significant chunk of work. hence we wanted to focus on the dask worker as an alternative, when people cannot use max_jobs.

**Comment by chasejohnson3** [comment]
I am looking into how to implement a list of jobs as an array job. It looks like asyncio repl would be a good way to check for a list of jobs every N seconds, but asyncio repl is only supported in Python 3.8+. The alternative to asyncio repl would be creating a thread to check for a list of jobs to be submitted, but I understand it is not good to mix asyncio and Threads.
(discussion of asyncio repl vs. Threads for Python 3.8 and 3.7: https://stackoverflow.com/questions/26270681/can-an-asyncio-event-loop-run-in-the-background-without-suspending-the-python-in)

My question is: Can I implement an SGEWorker using asyncio repl given it is only supported in Python 3.8+? I believe pydra requires 3.7+.

**Comment by hjmjohnson** [comment]
@chasejohnson3 Perhaps we could require Python 3.8+ if using SGE.  Not a great solution, but it might be a start.  Perhaps a module design where a good solution is available with Python 3.8, and a degraded option is available with Python 3.7?

**Comment by satra** [comment]
it is ok to restrict somethings to a newer version if it's much cleaner from an implementation perspective.

**Comment by chasejohnson3** [comment]
@satra @hjmjohnson I have implemented an SGEWorker that makes use of array jobs along with a few other features to allow scaling on a cluster using Sun Grid Engine. The PR is #472

**Comment by hjmjohnson** [comment]
#472 Has been merged.  Closing.
