### ISSUE TITLE
fixing file naming in output_file_template

### ISSUE THREAD

**Issue by djarecka** [nipype/pydra#314]
When file name with extension is modified in `output_file_template` the name is not modified correctly, see e.g. [test_wf_shell_cmd_3](https://github.com/nipype/pydra/blob/master/pydra/engine/tests/test_shelltask.py#L1646). 
The result, `res.output.cp_file`, is `.../newfile.txt_copy`

**Comment by satra** [comment]
unless you:

1. create a list of extensions this in general will be hard to do. (e.g. `.nii.gz` vs `.nii`). 
2. or you could require a metadata key, which if present will provide a possible list of extensions. otherwise it will assume the output from `os.path.splitext`. the latter should be fine in many cases, but we know that pydra will need to handle `.nii.gz`

**Comment by djarecka** [comment]
I implemented something for boutiques, let me copy that and see how this work
